feat: add send_queue and retry_on_failure options for otlp exporter
observeinc/helm-charts pull request #246
Opened 2024-10-16 20:14 UTC by obs-gh-alexlew

2024-10-16 23:04 UTC, arthur-observe approved these changes

2024-10-17 14:12 UTC, arthur-observe requested changes
Can you check examples/agent folder and see if any changes are needed there in provided values files

2024-10-17 17:18 UTC, obs-gh-alexlew commented
> Can you check examples/agent folder and see if any changes are needed there in provided values files

Just checked, none of the migrated fields are used in the examples

2024-10-17 20:49 UTC, arthur-observe approved these changes

2024-10-17 23:34 UTC, closed without merging